### ISSUE TITLE
Cant install vue-select

### ISSUE THREAD

**Issue by asbator** [coolsam726/jetstream-inertia-generator#24] opened 2021-09-16 07:37 UTC
During installation, when running:
npm install --include=dev --legacy-peer-deps savannabits/vue-select#v4.0.0-alpha.0

i get error:
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/savannabits/vue-select.git
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.

Can sagalbot/vue-select be used instead?

**Comment by coolsam726** [comment] 2021-09-16 07:46
Hi. This is actually a fork of sagalbot/vue-select that works with vue 3. Initially the package was using sagalbot's version but it does not support vue 3 and the vue3-compat feature had a bug.

Could you try omitting the package from the installation list and install it separately?

If it still throws an error could you be open to switch to yarn?

I will try to reproduce the error later today.

**Comment by asbator** [comment] 2021-09-16 13:28
Everything installs except vue-select 4.0
Yarn seems to install vue-select@3.11.2 instead.

**Comment by coolsam726** [comment] 2021-09-16 14:01
@asbator there is ongoing effort in [Vue Select to Support Vue 3](https://github.com/sagalbot/vue-select/pull/1344). I think it will be released soon as **vue-select@next**. For now kindly try to work with yarn since I don't think it has any issue with my fork of vue-select that supports vue3. Once vue-select@next is out I will update the documentation to use it. 

I just ran both of the following commands I don't seem to get any issue on my end:
```shell
yarn add savannabits/vue-select#v4.0.0-alpha.0
npm install savannabits/vue-select#v4.0.0-alpha.0
```

And you are right, `savannabits/vue-select#v4.0.0-alpha.0` is just a feat-compat branch release which uses the current version of `vue-select` under the hood.

**Closed by coolsam726** 2021-09-16 14:01 UTC
